language: ruby
rvm:
  - 2.1.0
  - 2.0.0
  - 1.9.3
  - jruby-head
  - rbx-2
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: rbx-2
script: bundle exec rake test
env:
  global:
    - "JRUBY_OPTS=-Xcext.enabled=true"